import React, { createContext, useContext, useState } from "react";

type Language = "en" | "es" | "pt-BR";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Barra Lateral
    "nav.home": "Home",
    "nav.courses": "Courses",
    "nav.analytics": "Analytics",
    "nav.certifications": "Certifications",
    "nav.settings": "Settings",
    "nav.support": "Support",
    "nav.notifications": "Notifications",
    "sidebar.startLearning": "Start Learning",
    "sidebar.learningPortal": "Learning Portal",

    // Barra Superior
    "topbar.search": "Search courses, analytics...",
    "topbar.profile": "Profile",
    "topbar.helpCenter": "Help Center",
    "topbar.expand": "Expand sidebar",
    "topbar.collapse": "Collapse sidebar",
    "topbar.lightMode": "Switch to light mode",
    "topbar.darkMode": "Switch to dark mode",

    // Início
    "home.welcomePrefix": "Welcome back,",
    "home.subtitle":
      "Explore available courses and follow your learning activities.",
    "home.currentTrack": "Current Track",
    "home.featuredCourses": "Featured Courses",
    "home.viewAll": "View all",
    "home.active": "Active",
    "home.thisMonth": "this month",
    "home.avgScore": "Avg Score",
    "home.acrossDepts": "Across depts",
    "home.recentActivity": "Recent Activity",
    "home.viewActivityLog": "View Activity Log",
    "home.videoSeries": "Video Series",
    "home.interactiveQuiz": "Interactive Quiz",
    "home.act1User": "Design Team",
    "home.act1Action": "completed",
    "home.act1Target": "Accessibility Guidelines",
    "home.act1Time": "2 hours ago",
    "home.act2User": "System",
    "home.act2Action": "assigned",
    "home.act2Target": "Compliance 2024",
    "home.act2Time": "Yesterday",
    "home.act3Action": "replied to",
    "home.act3Target": "Leadership 101",

    // Cursos
    "courses.title": "Available Courses",
    "courses.subtitle":
      "Explore and continue your learning journey to build new skills and advance your career at Trainify.",
    "courses.filterAll": "All",
    "courses.filterLeadership": "Leadership",
    "courses.filterTechnical": "Technical",
    "courses.filterSoftSkills": "Soft Skills",
    "courses.filterPublished": "Published",
    "courses.filterDraft": "Drafts",
    "courses.filterInProgress": "In Progress",
    "courses.filterCompleted": "Completed",
    "courses.filterNotStarted": "Not Started",
    "courses.badgeDraft": "Draft",
    "courses.seeResults": "See results",
    "courses.editCourse": "Edit Course",
    "courses.viewCourse": "View Course",
    "courses.lesson": "lesson",
    "courses.lessons": "lessons",
    "courses.loading": "Loading courses...",
    "courses.loadError": "Could not load the courses. Please try again.",
    "courses.enrollError": "Could not enroll you in this course. Please try again.",
    "courses.emptyStaff": "No courses yet. Use New Course to create the first one.",
    "courses.emptyStudent": "No courses available for you right now.",
    "courses.statusCompleted": "Completed",
    "courses.statusComplete": "Complete",
    "courses.statusNotStarted": "Not Started",
    "courses.reviewMaterial": "Review Material",
    "courses.resumeCourse": "Resume Course",
    "courses.startCourse": "Start Course",

    // Análises
    "analytics.title": "Analytics Overview",
    "analytics.subtitle":
      "Track learner engagement and performance metrics across departments.",
    "analytics.exportReport": "Export Report",
    "analytics.filterData": "Filter Data",
    "analytics.filtersTitle": "Filter data",
    "analytics.filtersDescription": "Narrows the learner table, the course completion list and the exported report. The charts above always show the whole company.",
    "analytics.filterCourse": "Course",
    "analytics.filterStatus": "Status",
    "analytics.filterSearch": "Learner",
    "analytics.filterSearchPlaceholder": "Name or e-mail",
    "analytics.filterAll": "All",
    "analytics.filterClear": "Clear filters",
    "analytics.filterApply": "Apply",
    "analytics.filterActive": "filter(s) active",
    "analytics.noMatches": "No enrollment matches the current filters.",
    "analytics.totalLearners": "Total Active Learners",
    "analytics.totalCourses": "Total Courses",
    "analytics.activeEnrollments": "Active Enrollments",
    "analytics.completedEnrollments": "Completed Enrollments",
    "analytics.avgScore": "Average Score",
    "analytics.avgTime": "Avg Time to Complete",
    "analytics.completionRate": "Completion Rate",
    "analytics.vsLastMonth": "vs last month",
    "analytics.engagementOverTime": "Engagement Over Time",
    "analytics.last30Days": "Last 30 Days",
    "analytics.lastQuarter": "Last Quarter",
    "analytics.yearToDate": "Year to Date",
    "analytics.courseDistribution": "Course Distribution",
    "analytics.enrollmentsByCategory": "Enrollments by category",
    "analytics.deptPerformance": "Department Performance",
    "analytics.learnerProgress": "Detailed Learner Progress",
    "analytics.viewAll": "View All",
    "analytics.colName": "Learner Name",
    "analytics.colCourse": "Current Course",
    "analytics.colProgress": "Progress",
    "analytics.colScore": "Score",
    "analytics.colStatus": "Status",
    "analytics.statusInProgress": "In Progress",
    "analytics.statusCompleted": "Completed",
    "analytics.statusStarted": "Started",
    "analytics.statusCancelled": "Cancelled",
    "analytics.enrollmentStatus": "Enrollment Status",
    "analytics.enrollmentsByStatus": "Enrollments by status",
    "analytics.courseCompletion": "Completion Rate by Course",
    "analytics.newEnrollments": "Enrollments",
    "analytics.completions": "Completions",
    "analytics.loading": "Loading...",
    "analytics.loadError": "Could not load the data",
    "analytics.noEnrollments": "No enrollments yet",
    "analytics.week1": "Week 1",
    "analytics.week2": "Week 2",
    "analytics.week3": "Week 3",
    "analytics.week4": "Week 4",
    "analytics.week5": "Week 5",
    "analytics.week6": "Week 6",
    "analytics.leadership": "Leadership",
    "analytics.technical": "Technical",
    "analytics.compliance": "Compliance",
    "analytics.softSkills": "Soft Skills",
    "analytics.deptEngineering": "Engineering",
    "analytics.deptSales": "Sales",
    "analytics.deptMarketing": "Marketing",
    "analytics.deptHR": "HR",
    "analytics.courseReact": "Advanced React Patterns",
    "analytics.courseSecurity": "Data Security Basics",
    "analytics.courseLeadership": "Leadership 101",

    // Certificações
    "cert.title": "Certifications & Awards",
    "cert.subtitle":
      "View and share your achievements and completed credentials.",
    "cert.downloadAll": "Download All",
    "cert.totalEarned": "Total Earned",
    "cert.hoursLogged": "Hours Logged",
    "cert.avgScore": "Avg. Score",
    "cert.yourCredentials": "Your Credentials",
    "cert.issued": "Issued",
    "cert.score": "Score",
    "cert.downloadPdf": "Download PDF",
    "cert.share": "Share",
    "cert.skillLeadership": "Leadership",
    "cert.skillTechnical": "Technical",
    "cert.skillCommunication": "Communication",
    "cert.skillCompliance": "Compliance",

    // Assistente de IA
    "nav.assistant": "IA Assistant",
    "ia.conversations": "Conversations",
    "ia.suggestedActions": "Suggested Actions",
    "ia.recent": "Recent",
    "ia.action1": "Generate Progress Report",
    "ia.action2": "Schedule Team Training",
    "ia.yesterday": "Yesterday",
    "ia.welcomeMessage":
      "Hello! I'm your Learning IA Assistant. I can help you build curriculums, analyze training data, or recommend courses for your team.\n\nHow can I assist you today?",
    "ia.assistantName": "IA Assistant",
    "ia.you": "You",
    "ia.inputPlaceholder":
      "Ask the IA Assistant to create plans, analyze data...",
    "ia.send": "Send",
    "ia.disclaimer":
      "IA Assistant can make mistakes. Consider verifying important data.",

    // Configurações
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account preferences.",
    "settings.profile": "My Profile",
    "settings.security": "Security",
    "settings.personalInfo": "Personal Information",
    "settings.fullName": "Full Name",
    "settings.email": "Email Address",
    "settings.bio": "Bio",
    "settings.bioPlaceholder": "Tell us about yourself...",
    "settings.save": "Save Changes",
    "settings.change": "Change",
    "settings.changePassword": "Change Password",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmNewPassword": "Confirm New Password",
    "settings.updatePassword": "Update Password",
    "settings.passwordMismatch": "Passwords do not match.",
    "settings.passwordUpdated": "Password updated.",
    "settings.passwordError": "Could not update the password. Try again.",

    // Suporte
    "support.heroTitle": "How can we help you?",
    "support.heroSubtitle":
      "Search our knowledge base or get in touch with our learning support team.",
    "support.searchPlaceholder": "Search for articles, guides, or questions...",
    "support.guideTitle": "Getting Started Guide",
    "support.guideDesc":
      "New to Trainify? Learn the basics of navigating the platform.",
    "support.troubleTitle": "Troubleshooting",
    "support.troubleDesc":
      "Fix common issues with video playback or quiz submissions.",
    "support.forumTitle": "Community Forum",
    "support.forumDesc":
      "Ask questions and discuss topics with other learners.",
    "support.contactTitle": "Contact Support",
    "support.contactSubtitle":
      "If you can't find what you are looking for, our support team is ready to help.",
    "support.emailSupport": "Email Support",
    "support.phoneSupport": "Phone Support",
    "support.faqTitle": "Frequently Asked Questions",
    "support.faq1Q": "How do I print or download my certificate?",
    "support.faq1A":
      "Navigate to the Certifications tab from the left menu. Find the credential you want to download and click the download icon located at the bottom right of the certification card.",
    "support.faq2Q": "Is there a limit on how many courses I can take?",
    "support.faq2A":
      "Available courses are listed on the Courses page. Contact your organization administrator for access questions.",
    "support.faq3Q": "I forgot my password, how do I reset it?",
    "support.faq3A":
      "On the login page, select Forgot password and enter your email to receive a reset link.",
    "support.faq4Q": "How often are the training materials updated?",
    "support.faq4A":
      "Course materials are managed by their instructors. Ask the instructor about updates.",

    // Perfil
    "profile.myProfile": "My Profile",
    "profile.logout": "Sign Out",

    // Avaliação
    "assessment.title": "Knowledge Check",
    "assessment.loading": "Loading assessment...",
    "assessment.loadError": "Could not load the assessment.",
    "assessment.submitError": "Could not submit your answers. Please try again.",
    "assessment.lockedError": "Finish the previous lesson to unlock this assessment.",
    "assessment.notConfigured": "Assessment not set up",
    "assessment.notConfiguredDesc": "This lesson has no questions yet.",
    "assessment.back": "Back",
    "assessment.start": "Start assessment",
    "assessment.tryAgain": "Try again",
    "assessment.submit": "Submit answers",
    "assessment.question": "question",
    "assessment.questions": "questions",
    "assessment.passingScore": "Passing score",
    "assessment.attemptsLeft": "Attempts left",
    "assessment.attempt": "Attempt",
    "assessment.alreadyPassed": "You already passed this assessment",
    "assessment.noAttemptsLeft": "You have used every attempt. Talk to your instructor.",
    "assessment.approved": "Approved!",
    "assessment.notApproved": "Not approved yet",
    "assessment.yourScore": "Your score",
    "assessment.of": "of",
    "assessment.correctAnswers": "correct",
    "assessment.review": "Answer review",
    "assessment.yourAnswer": "Your answer",
    "assessment.correctAnswer": "Correct answer",
    "assessment.noAnswer": "Not answered",
    "assessment.completed": "Assessment Completed!",
    "assessment.completedDesc":
      "Review your assessment result below.",
    "assessment.totalScore": "Total Score",
    "assessment.timeSpent": "Time Spent",
    "assessment.returnToCourse": "Return to Course",
    "assessment.questionOf": "Question {current} of {total}",
    "assessment.complete": "Complete",
    "assessment.selectHint":
      "Select your answer to proceed to the next question.",
    "assessment.next": "Next Question",
    "assessment.finish": "Finish Assessment",
    "assessment.q1Text":
      "Which component of the OODA loop is most heavily influenced by an individual's cultural heritage and previous experience?",
    "assessment.q1o1": "Observe",
    "assessment.q1o2": "Orient",
    "assessment.q1o3": "Decide",
    "assessment.q1o4": "Act",
    "assessment.q2Text":
      "In the Cynefin framework, which domain represents problems where cause-and-effect can only be determined after the fact?",
    "assessment.q2o1": "Simple",
    "assessment.q2o2": "Complicated",
    "assessment.q2o3": "Complex",
    "assessment.q2o4": "Chaotic",
    "assessment.q3Text":
      "What is the primary goal of applying the Five Whys technique in root cause analysis?",
    "assessment.q3o1": "To identify the team member at fault",
    "assessment.q3o2": "To find a temporary workaround quickly",
    "assessment.q3o3":
      "To peel back thin layers of symptoms to find the underlying issue",
    "assessment.q3o4": "To generate five alternative solutions",

    // Conteúdo do Curso

    // Notificações
    "notif.title": "Notifications",
    "notif.subtitle":
      "Stay updated with your latest learning activities and team alerts.",
    "notif.markAllRead": "Mark all read",
    "notif.clearAll": "Clear all",
  },

  es: {
    // Barra Lateral
    "nav.home": "Inicio",
    "nav.courses": "Cursos",
    "nav.analytics": "Análisis",
    "nav.certifications": "Certificaciones",
    "nav.settings": "Ajustes",
    "nav.support": "Soporte",
    "nav.notifications": "Notificaciones",
    "sidebar.startLearning": "Empezar a Aprender",
    "sidebar.learningPortal": "Portal de Aprendizaje",

    // Barra Superior
    "topbar.search": "Buscar cursos, análisis...",
    "topbar.profile": "Perfil",
    "topbar.helpCenter": "Centro de Ayuda",
    "topbar.expand": "Expandir menú lateral",
    "topbar.collapse": "Contraer menú lateral",
    "topbar.lightMode": "Cambiar a modo claro",
    "topbar.darkMode": "Cambiar a modo oscuro",

    // Início
    "home.welcomePrefix": "Bienvenido de nuevo,",
    "home.subtitle":
      "Explora los cursos disponibles y sigue tus actividades de aprendizaje.",
    "home.currentTrack": "Vía Actual",
    "home.featuredCourses": "Cursos Destacados",
    "home.viewAll": "Ver todos",
    "home.active": "Activos",
    "home.thisMonth": "este mes",
    "home.avgScore": "Puntaje Prom.",
    "home.acrossDepts": "En deptos",
    "home.recentActivity": "Actividad Reciente",
    "home.viewActivityLog": "Ver Registro de Actividad",
    "home.videoSeries": "Serie de Videos",
    "home.interactiveQuiz": "Quiz Interactivo",
    "home.act1User": "Equipo de Diseño",
    "home.act1Action": "completó",
    "home.act1Target": "Pautas de Accesibilidad",
    "home.act1Time": "Hace 2 horas",
    "home.act2User": "Sistema",
    "home.act2Action": "asignó",
    "home.act2Target": "Compliance 2024",
    "home.act2Time": "Ayer",
    "home.act3Action": "respondió",
    "home.act3Target": "Liderazgo 101",

    // Cursos
    "courses.title": "Cursos Disponibles",
    "courses.subtitle":
      "Explora y continúa tu viaje de aprendizaje para desarrollar nuevas habilidades y avanzar en tu carrera en Trainify.",
    "courses.filterAll": "Todos",
    "courses.filterLeadership": "Liderazgo",
    "courses.filterTechnical": "Técnico",
    "courses.filterSoftSkills": "Habilidades Blandas",
    "courses.filterPublished": "Publicados",
    "courses.filterDraft": "Borradores",
    "courses.filterInProgress": "En Progreso",
    "courses.filterCompleted": "Completados",
    "courses.filterNotStarted": "No Iniciados",
    "courses.badgeDraft": "Borrador",
    "courses.seeResults": "Ver resultados",
    "courses.editCourse": "Editar Curso",
    "courses.viewCourse": "Ver Curso",
    "courses.lesson": "leccion",
    "courses.lessons": "lecciones",
    "courses.loading": "Cargando cursos...",
    "courses.loadError": "No se pudieron cargar los cursos. Intentalo de nuevo.",
    "courses.enrollError": "No se pudo inscribirte en este curso. Intentalo de nuevo.",
    "courses.emptyStaff": "Aun no hay cursos. Usa Nuevo Curso para crear el primero.",
    "courses.emptyStudent": "No hay cursos disponibles para ti en este momento.",
    "courses.statusCompleted": "Completado",
    "courses.statusComplete": "Completado",
    "courses.statusNotStarted": "No Iniciado",
    "courses.reviewMaterial": "Revisar Material",
    "courses.resumeCourse": "Reanudar Curso",
    "courses.startCourse": "Comenzar Curso",

    // Análises
    "analytics.title": "Resumen de Análisis",
    "analytics.subtitle":
      "Sigue el compromiso y las métricas de rendimiento por departamento.",
    "analytics.exportReport": "Exportar Informe",
    "analytics.filterData": "Filtrar Datos",
    "analytics.filtersTitle": "Filtrar datos",
    "analytics.filtersDescription": "Acota la tabla de alumnos, la lista de finalización por curso y el informe exportado. Los gráficos de arriba siempre muestran toda la empresa.",
    "analytics.filterCourse": "Curso",
    "analytics.filterStatus": "Situación",
    "analytics.filterSearch": "Alumno",
    "analytics.filterSearchPlaceholder": "Nombre o correo",
    "analytics.filterAll": "Todos",
    "analytics.filterClear": "Limpiar filtros",
    "analytics.filterApply": "Aplicar",
    "analytics.filterActive": "filtro(s) activo(s)",
    "analytics.noMatches": "Ninguna inscripción coincide con los filtros actuales.",
    "analytics.totalLearners": "Total de Alumnos Activos",
    "analytics.totalCourses": "Total de Cursos",
    "analytics.activeEnrollments": "Matrículas Activas",
    "analytics.completedEnrollments": "Matrículas Completadas",
    "analytics.avgScore": "Puntuación Media",
    "analytics.avgTime": "Tiempo Promedio de Conclusión",
    "analytics.completionRate": "Tasa de Finalización",
    "analytics.vsLastMonth": "vs mes anterior",
    "analytics.engagementOverTime": "Compromiso a lo Largo del Tiempo",
    "analytics.last30Days": "Últimos 30 Días",
    "analytics.lastQuarter": "Último Trimestre",
    "analytics.yearToDate": "Año Actual",
    "analytics.courseDistribution": "Distribución de Cursos",
    "analytics.enrollmentsByCategory": "Matrículas por categoría",
    "analytics.deptPerformance": "Rendimiento por Departamento",
    "analytics.learnerProgress": "Progreso Detallado",
    "analytics.viewAll": "Ver Todos",
    "analytics.colName": "Nombre",
    "analytics.colCourse": "Curso Actual",
    "analytics.colProgress": "Progreso",
    "analytics.colScore": "Puntuación",
    "analytics.colStatus": "Estado",
    "analytics.statusInProgress": "En Progreso",
    "analytics.statusCompleted": "Completado",
    "analytics.statusStarted": "Iniciado",
    "analytics.statusCancelled": "Cancelado",
    "analytics.enrollmentStatus": "Estado de las Matrículas",
    "analytics.enrollmentsByStatus": "Matrículas por estado",
    "analytics.courseCompletion": "Tasa de Finalización por Curso",
    "analytics.newEnrollments": "Matrículas",
    "analytics.completions": "Finalizaciones",
    "analytics.loading": "Cargando...",
    "analytics.loadError": "No se pudieron cargar los datos",
    "analytics.noEnrollments": "Aún no hay matrículas",
    "analytics.week1": "Sem 1",
    "analytics.week2": "Sem 2",
    "analytics.week3": "Sem 3",
    "analytics.week4": "Sem 4",
    "analytics.week5": "Sem 5",
    "analytics.week6": "Sem 6",
    "analytics.leadership": "Liderazgo",
    "analytics.technical": "Técnico",
    "analytics.compliance": "Cumplimiento",
    "analytics.softSkills": "Habilidades Blandas",
    "analytics.deptEngineering": "Ingeniería",
    "analytics.deptSales": "Ventas",
    "analytics.deptMarketing": "Marketing",
    "analytics.deptHR": "RRHH",
    "analytics.courseReact": "Patrones Avanzados en React",
    "analytics.courseSecurity": "Seguridad de Datos",
    "analytics.courseLeadership": "Liderazgo 101",

    // Certificações
    "cert.title": "Certificaciones y Logros",
    "cert.subtitle": "Ve y comparte tus logros y credenciales completadas.",
    "cert.downloadAll": "Descargar Todo",
    "cert.totalEarned": "Total Obtenido",
    "cert.hoursLogged": "Horas Estudiadas",
    "cert.avgScore": "Puntuación Media",
    "cert.yourCredentials": "Tus Credenciales",
    "cert.issued": "Emitido el",
    "cert.score": "Puntuación",
    "cert.downloadPdf": "Descargar PDF",
    "cert.share": "Compartir",
    "cert.skillLeadership": "Liderazgo",
    "cert.skillTechnical": "Técnico",
    "cert.skillCommunication": "Comunicación",
    "cert.skillCompliance": "Cumplimiento",

    // Assistente de IA
    "nav.assistant": "Asistente IA",
    "ia.conversations": "Conversaciones",
    "ia.suggestedActions": "Acciones Sugeridas",
    "ia.recent": "Recientes",
    "ia.action1": "Generar Informe de Progreso",
    "ia.action2": "Programar Entrenamiento del Equipo",
    "ia.yesterday": "Ayer",
    "ia.welcomeMessage":
      "¡Hola! Soy tu Asistente de Aprendizaje IA. Puedo ayudarte a crear currículos, analizar datos de entrenamiento o recomendar cursos para tu equipo.\n\n¿Cómo puedo ayudarte hoy?",
    "ia.assistantName": "Asistente IA",
    "ia.you": "Tú",
    "ia.inputPlaceholder":
      "Pide al Asistente IA que cree planes, analice datos...",
    "ia.send": "Enviar",
    "ia.disclaimer":
      "El Asistente IA puede cometer errores. Considera verificar datos importantes.",

    // Configurações
    "settings.title": "Configuraciones",
    "settings.subtitle": "Gestiona las preferencias de tu cuenta.",
    "settings.profile": "Mi Perfil",
    "settings.security": "Seguridad",
    "settings.personalInfo": "Información Personal",
    "settings.fullName": "Nombre Completo",
    "settings.email": "Correo Electrónico",
    "settings.bio": "Biografía",
    "settings.bioPlaceholder": "Cuéntanos sobre ti...",
    "settings.save": "Guardar Cambios",
    "settings.change": "Cambiar",
    "settings.changePassword": "Cambiar Contraseña",
    "settings.currentPassword": "Contraseña Actual",
    "settings.newPassword": "Nueva Contraseña",
    "settings.confirmNewPassword": "Confirmar Nueva Contraseña",
    "settings.updatePassword": "Actualizar Contraseña",
    "settings.passwordMismatch": "Las contraseñas no coinciden.",
    "settings.passwordUpdated": "Contraseña actualizada.",
    "settings.passwordError": "No se pudo actualizar la contraseña. Inténtalo de nuevo.",

    // Notificações
    "notif.title": "Notificaciones",
    "notif.subtitle":
      "Mantente actualizado con tus actividades de aprendizaje y alertas del equipo.",
    "notif.markAllRead": "Marcar todas como leídas",
    "notif.clearAll": "Limpiar todo",

    // Suporte
    "support.heroTitle": "¿Cómo podemos ayudarte?",
    "support.heroSubtitle":
      "Busca en nuestra base de conocimiento o contáctanos.",
    "support.searchPlaceholder": "Buscar artículos, guías o preguntas...",
    "support.guideTitle": "Guía de Inicio",
    "support.guideDesc":
      "¿Nuevo en Trainify? Aprende lo básico sobre cómo navegar en la plataforma.",
    "support.troubleTitle": "Solución de Problemas",
    "support.troubleDesc":
      "Resuelve problemas comunes con la reproducción de video o envío de cuestionarios.",
    "support.forumTitle": "Foro de la Comunidad",
    "support.forumDesc": "Haz preguntas y discute temas con otros estudiantes.",
    "support.contactTitle": "Contactar Soporte",
    "support.contactSubtitle":
      "Si no encuentras lo que buscas, nuestro equipo está listo para ayudarte.",
    "support.emailSupport": "Soporte por Correo",
    "support.phoneSupport": "Soporte Telefónico",
    "support.faqTitle": "Preguntas Frecuentes",
    "support.faq1Q": "¿Cómo imprimo o descargo mi certificado?",
    "support.faq1A":
      "Ve a la pestaña Certificaciones en el menú izquierdo. Encuentra la credencial que deseas descargar y haz clic en el ícono de descarga en la esquina inferior derecha.",
    "support.faq2Q": "¿Hay un límite en la cantidad de cursos que puedo tomar?",
    "support.faq2A":
      "Los cursos disponibles aparecen en la página Cursos. Consulta al administrador de tu organización sobre el acceso.",
    "support.faq3Q": "Olvidé mi contraseña, ¿cómo la restablezco?",
    "support.faq3A":
      "En la página de inicio de sesión, selecciona Olvidé mi contraseña e introduce tu correo para recibir el enlace.",
    "support.faq4Q": "¿Con qué frecuencia se actualizan los materiales?",
    "support.faq4A":
      "Los responsables de cada curso gestionan los materiales. Consulta al instructor sobre las actualizaciones.",

    // Perfil
    "profile.myProfile": "Mi Perfil",
    "profile.logout": "Cerrar Sesión",

    // Avaliação
    "assessment.title": "Verificación de Conocimiento",
    "assessment.loading": "Cargando evaluacion...",
    "assessment.loadError": "No se pudo cargar la evaluacion.",
    "assessment.submitError": "No se pudieron enviar tus respuestas. Intentalo de nuevo.",
    "assessment.lockedError": "Termina la leccion anterior para desbloquear esta evaluacion.",
    "assessment.notConfigured": "Evaluacion no configurada",
    "assessment.notConfiguredDesc": "Esta leccion todavia no tiene preguntas.",
    "assessment.back": "Volver",
    "assessment.start": "Comenzar evaluacion",
    "assessment.tryAgain": "Intentar de nuevo",
    "assessment.submit": "Enviar respuestas",
    "assessment.question": "pregunta",
    "assessment.questions": "preguntas",
    "assessment.passingScore": "Nota minima",
    "assessment.attemptsLeft": "Intentos restantes",
    "assessment.attempt": "Intento",
    "assessment.alreadyPassed": "Ya aprobaste esta evaluacion",
    "assessment.noAttemptsLeft": "Usaste todos los intentos. Habla con tu instructor.",
    "assessment.approved": "Aprobado!",
    "assessment.notApproved": "Aun no aprobado",
    "assessment.yourScore": "Tu nota",
    "assessment.of": "de",
    "assessment.correctAnswers": "correctas",
    "assessment.review": "Revision de respuestas",
    "assessment.yourAnswer": "Tu respuesta",
    "assessment.correctAnswer": "Respuesta correcta",
    "assessment.noAnswer": "Sin responder",
    "assessment.completed": "¡Evaluación Completada!",
    "assessment.completedDesc":
      "Consulta el resultado de tu evaluación a continuación.",
    "assessment.totalScore": "Puntuación Total",
    "assessment.timeSpent": "Tiempo Empleado",
    "assessment.returnToCourse": "Volver al Curso",
    "assessment.questionOf": "Pregunta {current} de {total}",
    "assessment.complete": "Completado",
    "assessment.selectHint":
      "Selecciona tu respuesta para avanzar a la siguiente pregunta.",
    "assessment.next": "Siguiente Pregunta",
    "assessment.finish": "Finalizar Evaluación",
    "assessment.q1Text":
      "¿Qué componente del ciclo OODA está más influenciado por la herencia cultural y experiencia previa del individuo?",
    "assessment.q1o1": "Observar",
    "assessment.q1o2": "Orientar",
    "assessment.q1o3": "Decidir",
    "assessment.q1o4": "Actuar",
    "assessment.q2Text":
      "En el framework Cynefin, ¿qué dominio representa problemas donde la causa y efecto solo pueden determinarse después del hecho?",
    "assessment.q2o1": "Simple",
    "assessment.q2o2": "Complicado",
    "assessment.q2o3": "Complejo",
    "assessment.q2o4": "Caótico",
    "assessment.q3Text":
      "¿Cuál es el objetivo principal de aplicar la técnica de los Cinco Porqués en el análisis de causa raíz?",
    "assessment.q3o1": "Identificar al miembro del equipo responsable",
    "assessment.q3o2": "Encontrar rápidamente una solución temporal",
    "assessment.q3o3":
      "Eliminar capas de síntomas para encontrar el problema subyacente",
    "assessment.q3o4": "Generar cinco soluciones alternativas",

    // Conteúdo do Curso
  },

  "pt-BR": {
    // Barra Lateral
    "nav.home": "Início",
    "nav.courses": "Cursos",
    "nav.analytics": "Análises",
    "nav.certifications": "Certificados",
    "nav.settings": "Configurações",
    "nav.support": "Suporte",
    "nav.notifications": "Notificações",
    "sidebar.startLearning": "Começar a Aprender",
    "sidebar.learningPortal": "Portal de Ensino",

    // Barra Superior
    "topbar.search": "Pesquisar cursos, análises...",
    "topbar.profile": "Perfil",
    "topbar.helpCenter": "Central de Ajuda",
    "topbar.expand": "Expandir menu lateral",
    "topbar.collapse": "Recolher menu lateral",
    "topbar.lightMode": "Mudar para modo claro",
    "topbar.darkMode": "Mudar para modo escuro",

    // Início
    "home.welcomePrefix": "Bem-vindo de volta,",
    "home.subtitle":
      "Explore os cursos disponíveis e acompanhe suas atividades de aprendizado.",
    "home.currentTrack": "Trilha Atual",
    "home.featuredCourses": "Cursos em Destaque",
    "home.viewAll": "Ver todos",
    "home.active": "Ativos",
    "home.thisMonth": "este mês",
    "home.avgScore": "Nota Média",
    "home.acrossDepts": "Entre depts",
    "home.recentActivity": "Atividade Recente",
    "home.viewActivityLog": "Ver Histórico de Atividades",
    "home.videoSeries": "Série de Vídeos",
    "home.interactiveQuiz": "Quiz Interativo",
    "home.act1User": "Time de Design",
    "home.act1Action": "concluiu",
    "home.act1Target": "Diretrizes de Acessibilidade",
    "home.act1Time": "2 horas atrás",
    "home.act2User": "Sistema",
    "home.act2Action": "atribuiu",
    "home.act2Target": "Compliance 2024",
    "home.act2Time": "Ontem",
    "home.act3Action": "respondeu",
    "home.act3Target": "Liderança 101",

    // Cursos
    "courses.title": "Cursos Disponíveis",
    "courses.subtitle":
      "Explore e continue sua jornada de aprendizado para desenvolver novas habilidades e avançar em sua carreira na Trainify.",
    "courses.filterAll": "Todos",
    "courses.filterLeadership": "Liderança",
    "courses.filterTechnical": "Técnico",
    "courses.filterSoftSkills": "Soft Skills",
    "courses.filterPublished": "Publicados",
    "courses.filterDraft": "Rascunhos",
    "courses.filterInProgress": "Em Andamento",
    "courses.filterCompleted": "Concluídos",
    "courses.filterNotStarted": "Não Iniciados",
    "courses.badgeDraft": "Rascunho",
    "courses.seeResults": "Ver resultados",
    "courses.editCourse": "Editar Curso",
    "courses.viewCourse": "Ver Curso",
    "courses.lesson": "aula",
    "courses.lessons": "aulas",
    "courses.loading": "Carregando cursos...",
    "courses.loadError": "Não foi possível carregar os cursos. Tente novamente.",
    "courses.enrollError": "Não foi possível matricular você neste curso. Tente novamente.",
    "courses.emptyStaff": "Nenhum curso ainda. Use Novo Curso para criar o primeiro.",
    "courses.emptyStudent": "Nenhum curso disponível para você no momento.",
    "courses.statusCompleted": "Concluído",
    "courses.statusComplete": "Concluído",
    "courses.statusNotStarted": "Não Iniciado",
    "courses.reviewMaterial": "Revisar Material",
    "courses.resumeCourse": "Continuar Curso",
    "courses.startCourse": "Iniciar Curso",

    // Análises
    "analytics.title": "Visão Geral de Análises",
    "analytics.subtitle":
      "Acompanhe o engajamento e métricas de desempenho por departamento.",
    "analytics.exportReport": "Exportar Relatório",
    "analytics.filterData": "Filtrar Dados",
    "analytics.filtersTitle": "Filtrar dados",
    "analytics.filtersDescription": "Recorta a tabela de alunos, a conclusão por curso e o relatório exportado. Os gráficos acima sempre mostram a empresa inteira.",
    "analytics.filterCourse": "Curso",
    "analytics.filterStatus": "Situação",
    "analytics.filterSearch": "Aluno",
    "analytics.filterSearchPlaceholder": "Nome ou e-mail",
    "analytics.filterAll": "Todos",
    "analytics.filterClear": "Limpar filtros",
    "analytics.filterApply": "Aplicar",
    "analytics.filterActive": "filtro(s) ativo(s)",
    "analytics.noMatches": "Nenhuma matrícula corresponde aos filtros atuais.",
    "analytics.totalLearners": "Total de Alunos Ativos",
    "analytics.totalCourses": "Total de Cursos",
    "analytics.activeEnrollments": "Matrículas Ativas",
    "analytics.completedEnrollments": "Matrículas Concluídas",
    "analytics.avgScore": "Nota Média",
    "analytics.avgTime": "Tempo Médio de Conclusão",
    "analytics.completionRate": "Taxa de Conclusão",
    "analytics.vsLastMonth": "vs mês anterior",
    "analytics.engagementOverTime": "Engajamento ao Longo do Tempo",
    "analytics.last30Days": "Últimos 30 Dias",
    "analytics.lastQuarter": "Último Trimestre",
    "analytics.yearToDate": "Ano Atual",
    "analytics.courseDistribution": "Distribuição de Cursos",
    "analytics.enrollmentsByCategory": "Matrículas por categoria",
    "analytics.deptPerformance": "Desempenho por Departamento",
    "analytics.learnerProgress": "Progresso dos Alunos",
    "analytics.viewAll": "Ver Todos",
    "analytics.colName": "Nome",
    "analytics.colCourse": "Curso Atual",
    "analytics.colProgress": "Progresso",
    "analytics.colScore": "Nota",
    "analytics.colStatus": "Status",
    "analytics.statusInProgress": "Em Andamento",
    "analytics.statusCompleted": "Concluído",
    "analytics.statusStarted": "Iniciado",
    "analytics.statusCancelled": "Cancelado",
    "analytics.enrollmentStatus": "Status das Matrículas",
    "analytics.enrollmentsByStatus": "Matrículas por status",
    "analytics.courseCompletion": "Taxa de Conclusão por Curso",
    "analytics.newEnrollments": "Matrículas",
    "analytics.completions": "Conclusões",
    "analytics.loading": "Carregando...",
    "analytics.loadError": "Não foi possível carregar os dados",
    "analytics.noEnrollments": "Ainda não há matrículas",
    "analytics.week1": "Sem 1",
    "analytics.week2": "Sem 2",
    "analytics.week3": "Sem 3",
    "analytics.week4": "Sem 4",
    "analytics.week5": "Sem 5",
    "analytics.week6": "Sem 6",
    "analytics.leadership": "Liderança",
    "analytics.technical": "Técnico",
    "analytics.compliance": "Conformidade",
    "analytics.softSkills": "Soft Skills",
    "analytics.deptEngineering": "Engenharia",
    "analytics.deptSales": "Vendas",
    "analytics.deptMarketing": "Marketing",
    "analytics.deptHR": "RH",
    "analytics.courseReact": "Padrões Avançados em React",
    "analytics.courseSecurity": "Segurança de Dados",
    "analytics.courseLeadership": "Liderança 101",

    // Certificações
    "cert.title": "Certificações e Conquistas",
    "cert.subtitle":
      "Veja e compartilhe suas conquistas e credenciais concluídas.",
    "cert.downloadAll": "Baixar Todos",
    "cert.totalEarned": "Total Conquistado",
    "cert.hoursLogged": "Horas Estudadas",
    "cert.avgScore": "Nota Média",
    "cert.yourCredentials": "Suas Credenciais",
    "cert.issued": "Emitido em",
    "cert.score": "Nota",
    "cert.downloadPdf": "Baixar PDF",
    "cert.share": "Compartilhar",
    "cert.skillLeadership": "Liderança",
    "cert.skillTechnical": "Técnico",
    "cert.skillCommunication": "Comunicação",
    "cert.skillCompliance": "Conformidade",

    // Assistente de IA
    "nav.assistant": "Assistente IA",
    "ia.conversations": "Conversas",
    "ia.suggestedActions": "Ações Sugeridas",
    "ia.recent": "Recentes",
    "ia.action1": "Gerar Relatório de Progresso",
    "ia.action2": "Agendar Treinamento da Equipe",
    "ia.yesterday": "Ontem",
    "ia.welcomeMessage":
      "Olá! Sou seu Assistente de Aprendizado IA. Posso ajudar você a criar currículos, analisar dados de treinamento ou recomendar cursos para sua equipe.\n\nComo posso te ajudar hoje?",
    "ia.assistantName": "Assistente IA",
    "ia.you": "Você",
    "ia.inputPlaceholder":
      "Pergunte ao Assistente IA para criar planos, analisar dados...",
    "ia.send": "Enviar",
    "ia.disclaimer":
      "O Assistente IA pode cometer erros. Considere verificar informações importantes.",

    // Configurações
    "settings.title": "Configurações",
    "settings.subtitle": "Gerencie as preferências da sua conta.",
    "settings.profile": "Meu Perfil",
    "settings.security": "Segurança",
    "settings.personalInfo": "Informações Pessoais",
    "settings.fullName": "Nome Completo",
    "settings.email": "E-mail",
    "settings.bio": "Bio",
    "settings.bioPlaceholder": "Fale um pouco sobre você...",
    "settings.save": "Salvar Alterações",
    "settings.change": "Alterar",
    "settings.changePassword": "Alterar Senha",
    "settings.currentPassword": "Senha Atual",
    "settings.newPassword": "Nova Senha",
    "settings.confirmNewPassword": "Confirmar Nova Senha",
    "settings.updatePassword": "Atualizar Senha",
    "settings.passwordMismatch": "As senhas não coincidem.",
    "settings.passwordUpdated": "Senha atualizada.",
    "settings.passwordError": "Não foi possível atualizar a senha. Tente novamente.",

    // Suporte
    "support.heroTitle": "Como podemos te ajudar?",
    "support.heroSubtitle":
      "Pesquise na nossa base de conhecimento ou entre em contato com nosso time de suporte.",
    "support.searchPlaceholder": "Pesquisar artigos, guias ou dúvidas...",
    "support.guideTitle": "Guia de Primeiros Passos",
    "support.guideDesc":
      "Novo no Trainify? Aprenda o básico sobre como navegar na plataforma.",
    "support.troubleTitle": "Solução de Problemas",
    "support.troubleDesc":
      "Resolva problemas comuns com reprodução de vídeo ou envio de quizzes.",
    "support.forumTitle": "Fórum da Comunidade",
    "support.forumDesc": "Faça perguntas e discuta tópicos com outros alunos.",
    "support.contactTitle": "Contato com Suporte",
    "support.contactSubtitle":
      "Se não encontrar o que procura, nossa equipe está pronta para ajudar.",
    "support.emailSupport": "Suporte por E-mail",
    "support.phoneSupport": "Suporte por Telefone",
    "support.faqTitle": "Perguntas Frequentes",
    "support.faq1Q": "Como imprimo ou baixo meu certificado?",
    "support.faq1A":
      "Acesse a aba Certificados no menu lateral. Encontre a credencial que deseja baixar e clique no ícone de download no canto inferior direito do card.",
    "support.faq2Q": "Existe limite de cursos que posso fazer?",
    "support.faq2A":
      "Os cursos disponíveis podem ser consultados na página Cursos. Em caso de dúvidas sobre acesso, procure o administrador da sua organização.",
    "support.faq3Q": "Esqueci minha senha, como a redefino?",
    "support.faq3A":
      "Na tela de login, clique em Esqueceu a senha? e informe seu e-mail para receber o link de recuperação.",
    "support.faq4Q": "Com que frequência os materiais são atualizados?",
    "support.faq4A":
      "Os materiais são gerenciados pelos responsáveis por cada curso. Consulte o instrutor para saber sobre atualizações.",

    // Perfil
    "profile.myProfile": "Meu Perfil",
    "profile.logout": "Sair da conta",

    // Avaliação
    "assessment.title": "Verificação de Conhecimento",
    "assessment.loading": "Carregando avaliação...",
    "assessment.loadError": "Não foi possível carregar a avaliação.",
    "assessment.submitError": "Não foi possível enviar suas respostas. Tente novamente.",
    "assessment.lockedError": "Conclua a aula anterior para liberar esta avaliação.",
    "assessment.notConfigured": "Avaliação não configurada",
    "assessment.notConfiguredDesc": "Esta aula ainda não tem perguntas cadastradas.",
    "assessment.back": "Voltar",
    "assessment.start": "Iniciar avaliação",
    "assessment.tryAgain": "Tentar novamente",
    "assessment.submit": "Enviar respostas",
    "assessment.question": "pergunta",
    "assessment.questions": "perguntas",
    "assessment.passingScore": "Nota mínima",
    "assessment.attemptsLeft": "Tentativas restantes",
    "assessment.attempt": "Tentativa",
    "assessment.alreadyPassed": "Você já foi aprovado nesta avaliação",
    "assessment.noAttemptsLeft": "Você usou todas as tentativas. Procure o instrutor.",
    "assessment.approved": "Aprovado!",
    "assessment.notApproved": "Ainda não aprovado",
    "assessment.yourScore": "Sua nota",
    "assessment.of": "de",
    "assessment.correctAnswers": "corretas",
    "assessment.review": "Revisão das respostas",
    "assessment.yourAnswer": "Sua resposta",
    "assessment.correctAnswer": "Resposta correta",
    "assessment.noAnswer": "Não respondida",
    "assessment.completed": "Avaliação Concluída!",
    "assessment.completedDesc":
      "Confira abaixo o resultado da sua avaliação.",
    "assessment.totalScore": "Pontuação Total",
    "assessment.timeSpent": "Tempo Gasto",
    "assessment.returnToCourse": "Voltar ao Curso",
    "assessment.questionOf": "Questão {current} de {total}",
    "assessment.complete": "Concluído",
    "assessment.selectHint":
      "Selecione sua resposta para avançar para a próxima questão.",
    "assessment.next": "Próxima Questão",
    "assessment.finish": "Finalizar Avaliação",
    "assessment.q1Text":
      "Qual componente do ciclo OODA é mais influenciado pela herança cultural e experiência prévia do indivíduo?",
    "assessment.q1o1": "Observar",
    "assessment.q1o2": "Orientar",
    "assessment.q1o3": "Decidir",
    "assessment.q1o4": "Agir",
    "assessment.q2Text":
      "No framework Cynefin, qual domínio representa problemas onde a causa e efeito só podem ser determinados após o fato?",
    "assessment.q2o1": "Simples",
    "assessment.q2o2": "Complicado",
    "assessment.q2o3": "Complexo",
    "assessment.q2o4": "Caótico",
    "assessment.q3Text":
      "Qual é o objetivo principal de aplicar a técnica dos Cinco Porquês na análise de causa raiz?",
    "assessment.q3o1": "Identificar o membro da equipe responsável",
    "assessment.q3o2": "Encontrar rapidamente uma solução temporária",
    "assessment.q3o3":
      "Remover camadas de sintomas para encontrar o problema subjacente",
    "assessment.q3o4": "Gerar cinco soluções alternativas",

    // Conteúdo do Curso

    // Notificações
    "notif.title": "Notificações",
    "notif.subtitle":
      "Fique atualizado com suas atividades de aprendizado e alertas da equipe.",
    "notif.markAllRead": "Marcar todas como lidas",
    "notif.clearAll": "Limpar tudo",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "pt-BR";
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem("language", lang);
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
